/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define HAVE_INTTYPES_H 1

#define HAVE_STDINT_H 1

#define HAVE_STDLIB_H 1

#define HAVE_STRINGS_H 1

#define HAVE_STRING_H 1

#define HAVE_SYS_STAT_H 1

#define HAVE_SYS_TYPES_H 1

#define HAVE_UNISTD_H 1

#define PACKAGE_BUGREPORT "https://gitlab.freedesktop.org/spice/usbredir/issues"

#define PACKAGE_STRING "usbredir 0.12.0"

#define PACKAGE_VERSION "0.12.0"

#define USBREDIR_VISIBLE __attribute__((visibility ("default")))

#define VERSION "0.12.0"

